apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: project-composition
spec:
  compositeTypeRef: # Reference to the composite resource type this composition implements
    apiVersion: tetris.io/v1alpha1 # API version of the composite resource
    kind: Project # The kind of composite resource this composition handles
  mode: Pipeline # Execution mode - uses pipeline to chain composition functions
  pipeline:
    - step: create-a-project
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- range .observed.composite.resource.spec.namespaces }}
            ---
            apiVersion: kubernetes.crossplane.io/v1alpha2
            kind: Object
            metadata:
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: {{ . }}
              name: {{ . }}
            spec:
              providerConfigRef:
                name: kubernetes-provider
              forProvider:
                manifest:
                  apiVersion: v1
                  kind: Namespace
                  metadata:
                    name: {{ . }}
                    labels:
                      project: {{ $.observed.composite.resource.spec.name }}
            {{- end }}
    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: function-auto-ready
