{{ range $index,$element := .Values.apps }} 
{{ template "argocdvals" }}
  name: {{ $index }}
spec:
  destination:
    namespace: {{ $element.namespace }}
    server: {{ .server | default "https://kubernetes.default.svc" }}
  project: default
  source:
    path: {{ $element.path }}
    repoURL: {{ $element.repo }}
    targetRevision: {{ .targetRevision | default "HEAD" }}
  syncPolicy:
    automated: {}
{{ end }}
