apps:
  metrics-server:
    project: admin
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/metrics-server
    namespace: kube-system
  vpa:
    project: basic
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/vpa
    namespace: kube-system
    server: https://kubernetes.default.svc
  nsbasic:
    project: basic
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/namespaceChart
    namespace: kube-system
  nsadmin:
    project: admin
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/namespaceChart
    namespace: kube-system
