apps:
  metrics-server:
    project: admin
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/metrics-server
    namespace: kube-system
  vpa:
    project: admin
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/vpa
    namespace: kube-system
    server: https://kubernetes.default.svc
  promgw:
    project: basic
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/prometheus-pushgateway
    namespace: team1
    server: https://kubernetes.default.svc
  nsbasic:
    project: basic
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/namespaceChart
    namespace: kube-system
    helm:
      valueFiles: vars/kind.yaml
  nsadmin:
    project: admin
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/namespaceChart
    namespace: kube-system
  harbor-helm:
    project: admin
    repo: https://github.com/rjbrown57/wyk.git
    path: charts/harbor-helm
    namespace: kube-system
